Update action.yml

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -55,41 +55,26 @@ runs:
       if: steps.worker-check.outputs.has_changes == 'false'
       shell: bash
       run: bash ${{ github.action_path }}/summary-no-changes.bash
-      # run: |
-      #   TIME="$(date '+%F %T') (UTC)"
-      #   echo "[STEP] Print Summary (NO Changes) via Command ${TIME}"
-      #   TITLE="Auto Release"
-      #   MESSAGE="Release canceled because No Changes"
-      #   SUMMARY="[${TITLE} ${TIME}: ${MESSAGE}]"
-      #   echo "${SUMMARY}" >> $GITHUB_STEP_SUMMARY
-      #   echo "${SUMMARY}"
-      #   echo "summary=${SUMMARY}" >> $GITHUB_OUTPUT
     
     - name: "[STEP] Worker (Info) via Bash Script"
       id: worker-info
       if: steps.worker-check.outputs.has_changes == 'true'
       shell: bash
-      run: ${{ github.action_path }}/worker-info.bash
-      # run: |
-      #   echo "[STEP] Run Worker (Info) via Command $(date '+%F %T') (UTC)"
-      #   TODAY=$(date '+%Y.%m.%d')
-      #   TAG="${TODAY}.auto"
-      #   echo "release_tag=${TAG}" >> $GITHUB_OUTPUT
-      #   TIME="$(date '+%F %T') (UTC)"
-      #   echo "time=${TIME}" >> $GITHUB_OUTPUT
+      run: bash ${{ github.action_path }}/worker-info.bash
 
-    - name: "[STEP] Remove Existent Release via Command"
-      id: Remove
+    - name: "[STEP] Remove Existent Release via Bash Script"
+      id: remove
       if: steps.worker-check.outputs.has_changes == 'true'
       shell: bash
+      run: bash ${{ github.action_path }}/remove.bash
       env:
         GH_TOKEN: ${{ inputs.GITHUB_TOKEN }}
-      run: |
-        echo "[STEP] Remove Existent Release via Command $(date '+%F %T') (UTC)"
-        gh release delete ${{ steps.worker-info.outputs.tag }} --yes --cleanup-tag 2>/dev/null || echo ""
-        echo "[STEP] Create New Release via Action $(date '+%F %T') (UTC)"
+      # run: |
+      #   echo "[STEP] Remove Existent Release via Command $(date '+%F %T') (UTC)"
+      #   gh release delete ${{ steps.worker-info.outputs.tag }} --yes --cleanup-tag 2>/dev/null || echo ""
+      #   echo "[STEP] Create New Release via Action $(date '+%F %T') (UTC)"
       
-    - name: "[STEP] Create New Release via Action"
+    - name: "[STEP] Create New Release via SoftProps Action"
       id: Create
       if: steps.worker-check.outputs.has_changes == 'true'
       uses: softprops/action-gh-release@master
@@ -104,16 +89,17 @@ runs:
         draft: false
         prerelease: false
 
-    - name: "[STEP] Print Summary (Has Changes) via Command"
-      id: Summary-has_changes
+    - name: "[STEP] Print Summary (Has Changes) via Bash Script"
+      id: summary-has-changes
       if: steps.worker-check.outputs.has_changes == 'true'
       shell: bash
-      run: |
-        TIME="$(date '+%F %T') (UTC)"
-        echo "[STEP] Print Summary (Has Changes) via Command ${TIME}"
-        TITLE="Auto Release"
-        MESSAGE="Tag is <${{ steps.worker-info.outputs.tag }}>, Time is <${{ steps.worker-info.outputs.time }}>."
-        SUMMARY="[${TITLE}] ${TIME}: ${MESSAGE}"
-        echo "${SUMMARY}" >> $GITHUB_STEP_SUMMARY
-        echo "${SUMMARY}"
-        echo "summary=${SUMMARY}" >> $GITHUB_OUTPUT
+      run: bash ${{ github.action_path }}/summary-has-changes.bash
+      # run: |
+      #   TIME="$(date '+%F %T') (UTC)"
+      #   echo "[STEP] Print Summary (Has Changes) via Command ${TIME}"
+      #   TITLE="Auto Release"
+      #   MESSAGE="Tag is <${{ steps.worker-info.outputs.tag }}>, Time is <${{ steps.worker-info.outputs.time }}>."
+      #   SUMMARY="[${TITLE}] ${TIME}: ${MESSAGE}"
+      #   echo "${SUMMARY}" >> $GITHUB_STEP_SUMMARY
+      #   echo "${SUMMARY}"
+      #   echo "summary=${SUMMARY}" >> $GITHUB_OUTPUT
